# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from iris3d.v1 import scene_pb2 as iris3d_dot_v1_dot_scene__pb2


class SceneServiceStub(object):
    """SceneService is the ingest and lifecycle surface for objects held in the
    iris3d scene.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadObject = channel.stream_unary(
                '/iris3d.v1.SceneService/UploadObject',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.UploadObjectRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.UploadObjectResponse.FromString,
                _registered_method=True)
        self.CreateObject = channel.unary_unary(
                '/iris3d.v1.SceneService/CreateObject',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.FromString,
                _registered_method=True)
        self.SetParent = channel.unary_unary(
                '/iris3d.v1.SceneService/SetParent',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.SetParentRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.SetParentResponse.FromString,
                _registered_method=True)
        self.SetTransform = channel.unary_unary(
                '/iris3d.v1.SceneService/SetTransform',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/iris3d.v1.SceneService/ListObjects',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.DeleteObject = channel.unary_unary(
                '/iris3d.v1.SceneService/DeleteObject',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.FromString,
                _registered_method=True)


class SceneServiceServicer(object):
    """SceneService is the ingest and lifecycle surface for objects held in the
    iris3d scene.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.
    """

    def UploadObject(self, request_iterator, context):
        """Uploads a single object as a stream of chunks.

        The first message on the stream MUST carry `header`; every subsequent
        message MUST carry `chunk`. Chunks are written into the buffers declared
        by the header, and the upload is only committed to the scene once every
        declared buffer has received exactly its `byte_length` bytes. A stream
        that ends early, overruns a buffer, or arrives out of order is rejected
        and nothing is added to the scene.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateObject(self, request, context):
        """Creates an object that holds no data.

        Objects form a tree, and an empty object is how you make a pure grouping
        node: parent several objects to it and they share its transform. There is
        no separate "group" type — anything can parent anything, so a mesh may
        equally be the parent of a field that should follow it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParent(self, request, context):
        """Moves an object within the tree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransform(self, request, context):
        """Sets an object's local placement, relative to its parent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Lists the objects currently present in the scene.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Removes an object from the scene, releasing its buffers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadObject': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.UploadObjectRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.UploadObjectResponse.SerializeToString,
            ),
            'CreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateObject,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.SerializeToString,
            ),
            'SetParent': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParent,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.SetParentRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.SetParentResponse.SerializeToString,
            ),
            'SetTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransform,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iris3d.v1.SceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iris3d.v1.SceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneService(object):
    """SceneService is the ingest and lifecycle surface for objects held in the
    iris3d scene.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.
    """

    @staticmethod
    def UploadObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/iris3d.v1.SceneService/UploadObject',
            iris3d_dot_v1_dot_scene__pb2.UploadObjectRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.UploadObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/CreateObject',
            iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/SetParent',
            iris3d_dot_v1_dot_scene__pb2.SetParentRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.SetParentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/SetTransform',
            iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ListObjects',
            iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/DeleteObject',
            iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
