# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from iris3d.v1 import scene_pb2 as iris3d_dot_v1_dot_scene__pb2


class SceneServiceStub(object):
    """SceneService is the whole surface of the iris3d scene: what is in it, where
    it sits, and how it is drawn.

    Things are kept apart, and the splits are the reason the API looks the way it
    does.

    **Data** is arrays and nothing more. UploadData takes them in and hands back a
    handle each; no object appears, nothing is drawn, and the name on an array is
    a label rather than a role. One array can feed several representations, and a
    representation can read arrays that arrived at different times, so tying data
    to the thing that draws it would be the wrong shape.

    An **object** is a place in the tree and a name. It holds no data at all.

    An **actor** is one way of drawing something, a thing in its own right with
    its own handle. It is a child of the object it appears under, and it binds the
    arrays it reads to the inputs its kind declares. Showing one array in two
    places is two actors binding it under two parents. A **subset** narrows an
    actor to part of what it binds, which is what makes several worth having —
    one structure drawn as cartoon over its protein and as sticks over its
    ligand.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.

    The same position is taken wherever a question could be answered on either
    side. Selections arrive as index or mask arrays rather than as a query
    language, because a client already holds the structure needed to express
    "chain A" far better than a grammar invented here could. And nothing is
    inferred from what an array is called: a representation declares the element
    types and shapes it accepts, and a client binds whatever it uploaded.

    What can be drawn is not fixed by this schema. Actor kinds come from
    whichever rendering backends the server was built with, so ask
    ListActorKinds rather than carrying a table that will go stale.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadData = channel.stream_unary(
                '/iris3d.v1.SceneService/UploadData',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.UploadDataRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.UploadDataResponse.FromString,
                _registered_method=True)
        self.ListData = channel.unary_unary(
                '/iris3d.v1.SceneService/ListData',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ListDataRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ListDataResponse.FromString,
                _registered_method=True)
        self.ReleaseData = channel.unary_unary(
                '/iris3d.v1.SceneService/ReleaseData',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ReleaseDataRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ReleaseDataResponse.FromString,
                _registered_method=True)
        self.CreateObject = channel.unary_unary(
                '/iris3d.v1.SceneService/CreateObject',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.FromString,
                _registered_method=True)
        self.SetParent = channel.unary_unary(
                '/iris3d.v1.SceneService/SetParent',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.SetParentRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.SetParentResponse.FromString,
                _registered_method=True)
        self.SetTransform = channel.unary_unary(
                '/iris3d.v1.SceneService/SetTransform',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/iris3d.v1.SceneService/ListObjects',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.DeleteObject = channel.unary_unary(
                '/iris3d.v1.SceneService/DeleteObject',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.FromString,
                _registered_method=True)
        self.AddActor = channel.unary_unary(
                '/iris3d.v1.SceneService/AddActor',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.AddActorRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.AddActorResponse.FromString,
                _registered_method=True)
        self.SetActor = channel.unary_unary(
                '/iris3d.v1.SceneService/SetActor',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.SetActorRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.SetActorResponse.FromString,
                _registered_method=True)
        self.RemoveActor = channel.unary_unary(
                '/iris3d.v1.SceneService/RemoveActor',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.RemoveActorRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.RemoveActorResponse.FromString,
                _registered_method=True)
        self.ListActors = channel.unary_unary(
                '/iris3d.v1.SceneService/ListActors',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ListActorsRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ListActorsResponse.FromString,
                _registered_method=True)
        self.ListActorKinds = channel.unary_unary(
                '/iris3d.v1.SceneService/ListActorKinds',
                request_serializer=iris3d_dot_v1_dot_scene__pb2.ListActorKindsRequest.SerializeToString,
                response_deserializer=iris3d_dot_v1_dot_scene__pb2.ListActorKindsResponse.FromString,
                _registered_method=True)


class SceneServiceServicer(object):
    """SceneService is the whole surface of the iris3d scene: what is in it, where
    it sits, and how it is drawn.

    Things are kept apart, and the splits are the reason the API looks the way it
    does.

    **Data** is arrays and nothing more. UploadData takes them in and hands back a
    handle each; no object appears, nothing is drawn, and the name on an array is
    a label rather than a role. One array can feed several representations, and a
    representation can read arrays that arrived at different times, so tying data
    to the thing that draws it would be the wrong shape.

    An **object** is a place in the tree and a name. It holds no data at all.

    An **actor** is one way of drawing something, a thing in its own right with
    its own handle. It is a child of the object it appears under, and it binds the
    arrays it reads to the inputs its kind declares. Showing one array in two
    places is two actors binding it under two parents. A **subset** narrows an
    actor to part of what it binds, which is what makes several worth having —
    one structure drawn as cartoon over its protein and as sticks over its
    ligand.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.

    The same position is taken wherever a question could be answered on either
    side. Selections arrive as index or mask arrays rather than as a query
    language, because a client already holds the structure needed to express
    "chain A" far better than a grammar invented here could. And nothing is
    inferred from what an array is called: a representation declares the element
    types and shapes it accepts, and a client binds whatever it uploaded.

    What can be drawn is not fixed by this schema. Actor kinds come from
    whichever rendering backends the server was built with, so ask
    ListActorKinds rather than carrying a table that will go stale.
    """

    def UploadData(self, request_iterator, context):
        """Uploads arrays and nothing else.

        No object, no place in the tree, nothing drawn. Each array comes back with
        a handle, and an actor is built by binding those handles to the inputs its
        kind declares — see ListActorKinds for what each one accepts.

        A name in the header is a label, for the inventory and for a person reading
        it. It is not a role: what an array *is* to a representation is settled when
        it is bound, not guessed from what it was called. Upload the same array once
        and bind it to as many actors as you like.

        The first message MUST carry `header`; every later one MUST carry `chunk`,
        addressing an array by its index in the header. Nothing is committed until
        every declared array has received exactly its `byte_length` bytes, so a
        stream that ends early, overruns, or arrives out of order leaves the scene
        untouched.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListData(self, request, context):
        """Lists the arrays currently held, whether or not anything draws them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseData(self, request, context):
        """Forgets arrays.

        The bytes go when nothing refers to them any more, so releasing a handle an
        actor still uses frees nothing until that actor goes too. A handle that was
        already gone is not an error; the response says what was actually held.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateObject(self, request, context):
        """Creates an object that holds no data.

        Objects form a tree, and an empty object is how you make a pure grouping
        node: parent several objects to it and they share its transform. There is
        no separate "group" type — anything can parent anything, so a mesh may
        equally be the parent of a field that should follow it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParent(self, request, context):
        """Moves an object within the tree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransform(self, request, context):
        """Sets an object's local placement, relative to its parent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Lists the objects currently present in the scene.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """Removes one object from the scene.

        Deletes exactly what is named, and nothing else. Every child survives it,
        in the way that suits what it is: a child object becomes a root, since its
        transform is a place it still occupies; a child actor is detached and
        stops being drawn, since its transform is only an offset from the object
        it was under. A detached actor keeps its arrays and settings and can be
        placed again with SetActor.

        No arrays are freed either; ReleaseData is what does that, and RemoveActor
        is what destroys an actor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddActor(self, request, context):
        """Draws something under an object.

        Adds; it does not replace. An object may carry any number of actors at
        once — a protein as cartoon and as licorice, a mesh as surface and as
        wireframe — and each is configured independently.

        `parent` says where it appears, and an absent one is created for you.
        *What* it draws is in `params`, as arrays bound to the inputs its kind
        declares, so showing one array in two places is two actors binding it
        under two parents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActor(self, request, context):
        """Changes an existing actor. Only what is named is altered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveActor(self, request, context):
        """Removes one actor, leaving the object it was drawn under alone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActors(self, request, context):
        """Lists actors, optionally only those drawn under one object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActorKinds(self, request, context):
        """Lists the ways of drawing this build actually supports.

        Kinds are contributed by whichever rendering backends are compiled in
        rather than fixed by the schema, so a client that asks cannot offer a
        choice that silently does nothing — and needs no hardcoded table of its
        own.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadData': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadData,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.UploadDataRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.UploadDataResponse.SerializeToString,
            ),
            'ListData': grpc.unary_unary_rpc_method_handler(
                    servicer.ListData,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ListDataRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ListDataResponse.SerializeToString,
            ),
            'ReleaseData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseData,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ReleaseDataRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ReleaseDataResponse.SerializeToString,
            ),
            'CreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateObject,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.SerializeToString,
            ),
            'SetParent': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParent,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.SetParentRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.SetParentResponse.SerializeToString,
            ),
            'SetTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransform,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'AddActor': grpc.unary_unary_rpc_method_handler(
                    servicer.AddActor,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.AddActorRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.AddActorResponse.SerializeToString,
            ),
            'SetActor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActor,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.SetActorRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.SetActorResponse.SerializeToString,
            ),
            'RemoveActor': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveActor,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.RemoveActorRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.RemoveActorResponse.SerializeToString,
            ),
            'ListActors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActors,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ListActorsRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ListActorsResponse.SerializeToString,
            ),
            'ListActorKinds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActorKinds,
                    request_deserializer=iris3d_dot_v1_dot_scene__pb2.ListActorKindsRequest.FromString,
                    response_serializer=iris3d_dot_v1_dot_scene__pb2.ListActorKindsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iris3d.v1.SceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iris3d.v1.SceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneService(object):
    """SceneService is the whole surface of the iris3d scene: what is in it, where
    it sits, and how it is drawn.

    Things are kept apart, and the splits are the reason the API looks the way it
    does.

    **Data** is arrays and nothing more. UploadData takes them in and hands back a
    handle each; no object appears, nothing is drawn, and the name on an array is
    a label rather than a role. One array can feed several representations, and a
    representation can read arrays that arrived at different times, so tying data
    to the thing that draws it would be the wrong shape.

    An **object** is a place in the tree and a name. It holds no data at all.

    An **actor** is one way of drawing something, a thing in its own right with
    its own handle. It is a child of the object it appears under, and it binds the
    arrays it reads to the inputs its kind declares. Showing one array in two
    places is two actors binding it under two parents. A **subset** narrows an
    actor to part of what it binds, which is what makes several worth having —
    one structure drawn as cartoon over its protein and as sticks over its
    ligand.

    Data is described in the style of a numpy array — a raw little-endian byte
    buffer plus a dtype and a shape — rather than as `repeated` scalar fields.
    This keeps large uploads compact on the wire, keeps decoding cheap in every
    client language, and lets iris3d accept data in formats it will never
    implement a parser for: a client parses locally and pushes the arrays.

    The same position is taken wherever a question could be answered on either
    side. Selections arrive as index or mask arrays rather than as a query
    language, because a client already holds the structure needed to express
    "chain A" far better than a grammar invented here could. And nothing is
    inferred from what an array is called: a representation declares the element
    types and shapes it accepts, and a client binds whatever it uploaded.

    What can be drawn is not fixed by this schema. Actor kinds come from
    whichever rendering backends the server was built with, so ask
    ListActorKinds rather than carrying a table that will go stale.
    """

    @staticmethod
    def UploadData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/iris3d.v1.SceneService/UploadData',
            iris3d_dot_v1_dot_scene__pb2.UploadDataRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.UploadDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ListData',
            iris3d_dot_v1_dot_scene__pb2.ListDataRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ListDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ReleaseData',
            iris3d_dot_v1_dot_scene__pb2.ReleaseDataRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ReleaseDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/CreateObject',
            iris3d_dot_v1_dot_scene__pb2.CreateObjectRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.CreateObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/SetParent',
            iris3d_dot_v1_dot_scene__pb2.SetParentRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.SetParentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/SetTransform',
            iris3d_dot_v1_dot_scene__pb2.SetTransformRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.SetTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ListObjects',
            iris3d_dot_v1_dot_scene__pb2.ListObjectsRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/DeleteObject',
            iris3d_dot_v1_dot_scene__pb2.DeleteObjectRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.DeleteObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/AddActor',
            iris3d_dot_v1_dot_scene__pb2.AddActorRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.AddActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/SetActor',
            iris3d_dot_v1_dot_scene__pb2.SetActorRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.SetActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/RemoveActor',
            iris3d_dot_v1_dot_scene__pb2.RemoveActorRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.RemoveActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ListActors',
            iris3d_dot_v1_dot_scene__pb2.ListActorsRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ListActorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActorKinds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris3d.v1.SceneService/ListActorKinds',
            iris3d_dot_v1_dot_scene__pb2.ListActorKindsRequest.SerializeToString,
            iris3d_dot_v1_dot_scene__pb2.ListActorKindsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
