[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", features = ["dynamic_linking"] }
bevy_egui = "0.41.1"
clap = { version = "4.5", features = ["derive"] }
prost = "0.14.3"
tokio = {"version" = "1.49.0", "features" = ["rt-multi-thread", "macros", "net", "time", "sync"]}
tonic = "0.14.5"
tonic-build = "0.14.5"
tonic-prost = "0.14.5"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
futures = "0.3.32"
tokio-stream = "0.1.18"
crossbeam-channel = "0.5.15"



[build-dependencies]
tonic-prost-build = "0.14.5"
glob = "0.3.3"


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
