[package]
name = "iris3d-grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
iris3d-core = { workspace = true }
iris3d-model = { workspace = true }
iris3d-scene = { workspace = true }
iris3d-filter = { workspace = true }

bevy = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
futures = { workspace = true }
async-stream = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
glob = { workspace = true }
