[build-system]
requires = ["uv_build >= 0.10.0, <0.11.0"]
build-backend = "uv_build"

[project]
name = "iris3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grpcio>=1.78.1",
    "numpy>=2.4.2",
    "protobuf>=6.33.5",
    "types-protobuf>=6.32.1.20260221",
]

[dependency-groups]
dev = [
    "biotite>=1.7.1",
    "grpcio-tools>=1.78.1",
]
